### ISSUE TITLE
Update "README" 

### ISSUE THREAD

**Issue by JavaScriptErika** [CascadingCoders/LandingPage#2]
Update README

- Add Cascading Coder's logo

- Add in Emojis throughout text - don't go too overboard, but enough to make it fun

- Add in Who We Are text (see issue #1 for text)

- See if you can make the markdown display the colors in the style guide section - if not, it's ok! If you know of another way or have a different idea, cool!

- Feel free to reorder as you see fit.

**Comment by JavaScriptErika** [comment]
![banner](https://user-images.githubusercontent.com/19316487/66330366-40528d80-e8fe-11e9-9375-4ddb13d3b983.jpg)

**Comment by Guilleo03** [comment]
I´ll take it
